name: GJLOP_CICD_BACK
on:
  push:
      branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm i -g npm@latest
      - run: npm i --only=prod

      - name: Upload files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_LOGIN }}
          password: ${{ secrets.FTP_PWD }}
          protocol: ftps
          port: 21
          local-dir: ./
          server-dir: ./
          log-level: minimal
          # dangerous-clean-slate: true

